use_frameworks!

platform :ios, '13.0'

target 'XDCard_Example' do
  pod 'XDCard', :path => '../'

  target 'XDCard_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
